"""Local preview server for the static H5 page.

Usage:
    uv run python h5_server.py
    uv run python h5_server.py --port 8765

The GitHub Pages build uses static JSON generated by export_web_data.py.
This server still exposes a small legacy JSON API for local debugging:
    GET /api/dates
    GET /api/stocks?date=YYYYMMDD
    GET /api/search?q=301297
"""

from __future__ import annotations

import argparse
import json
import re
import sqlite3
from http import HTTPStatus
from http.server import SimpleHTTPRequestHandler, ThreadingHTTPServer
from pathlib import Path
from urllib.parse import parse_qs, urlparse

import pandas as pd

from search_stock_csv import order_columns, read_csv, relative_path, search_csvs
from store.db import connect as db_connect, DB_PATH


ROOT = Path(__file__).resolve().parent
WEB_DIR = ROOT / "web"
DATA_DIR = ROOT / "data"
DATE_RE = re.compile(r"(?<!\d)(20\d{6})(?!\d)")


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Serve the stock CSV H5 page.")
    parser.add_argument("--host", default="127.0.0.1")
    parser.add_argument("--port", default=8765, type=int)
    parser.add_argument("--data-dir", default=DATA_DIR, type=Path)
    return parser.parse_args()


def csv_date(path: Path) -> str | None:
    match = DATE_RE.search(path.name)
    return match.group(1) if match else None


def csv_files(data_dir: Path) -> list[Path]:
    if not data_dir.exists():
        return []
    return sorted(data_dir.rglob("*.csv"))


def date_entries(data_dir: Path) -> list[dict[str, object]]:
    grouped: dict[str, list[Path]] = {}
    for path in csv_files(data_dir):
        date = csv_date(path)
        if not date:
            continue
        grouped.setdefault(date, []).append(path)

    entries = []
    for date in sorted(grouped, reverse=True):
        files = grouped[date]
        entries.append(
            {
                "date": date,
                "files": [relative_path(path) for path in files],
                "file_count": len(files),
            }
        )
    return entries


def combine_files(paths: list[Path]) -> pd.DataFrame:
    frames = []
    for path in paths:
        df = read_csv(path)
        df.insert(0, "source_file", relative_path(path))
        frames.append(df)

    if not frames:
        return pd.DataFrame()

    combined = pd.concat(frames, ignore_index=True, sort=False)
    return order_columns(combined)


def frame_payload(df: pd.DataFrame) -> dict[str, object]:
    if df.empty:
        return {"columns": [], "rows": []}

    safe_df = df.fillna("")
    return {
        "columns": list(safe_df.columns),
        "rows": safe_df.to_dict(orient="records"),
    }


class H5Handler(SimpleHTTPRequestHandler):
    data_dir = DATA_DIR

    def __init__(self, *args, **kwargs):
        super().__init__(*args, directory=str(WEB_DIR), **kwargs)

    def do_GET(self) -> None:
        parsed = urlparse(self.path)
        if parsed.path == "/api/dates":
            self.send_json(self.handle_dates())
            return
        if parsed.path == "/api/stocks":
            params = parse_qs(parsed.query)
            self.send_json(self.handle_stocks(params))
            return
        if parsed.path == "/api/search":
            params = parse_qs(parsed.query)
            self.send_json(self.handle_search(params))
            return
        if parsed.path == "/api/kline":
            params = parse_qs(parsed.query)
            self.send_json(self.handle_kline(params))
            return
        if parsed.path == "/":
            self.path = "/index.html"
        super().do_GET()

    def handle_dates(self) -> dict[str, object]:
        entries = date_entries(self.data_dir)
        return {
            "dates": entries,
            "latest_date": entries[0]["date"] if entries else None,
        }

    def handle_stocks(self, params: dict[str, list[str]]) -> tuple[dict[str, object], int]:
        requested_date = params.get("date", [None])[0]
        entries = date_entries(self.data_dir)
        allowed_dates = {entry["date"] for entry in entries}

        if not entries:
            return {
                "error": "No dated CSV files found under data/.",
                "dates": [],
                "latest_date": None,
                "date": None,
                "columns": [],
                "rows": [],
                "files": [],
            }, HTTPStatus.NOT_FOUND

        date = requested_date or entries[0]["date"]
        if date not in allowed_dates:
            return {
                "error": f"Date {date} is not available.",
                "dates": entries,
                "latest_date": entries[0]["date"],
            }, HTTPStatus.BAD_REQUEST

        paths = [path for path in csv_files(self.data_dir) if csv_date(path) == date]
        df = combine_files(paths)
        payload = frame_payload(df)
        payload.update(
            {
                "mode": "date",
                "date": date,
                "dates": entries,
                "latest_date": entries[0]["date"],
                "files": [relative_path(path) for path in paths],
                "row_count": len(df),
            }
        )
        return payload, HTTPStatus.OK

    def handle_search(self, params: dict[str, list[str]]) -> tuple[dict[str, object], int]:
        query = params.get("q", [""])[0].strip()
        entries = date_entries(self.data_dir)
        if not query:
            return {
                "error": "Search query is required.",
                "dates": entries,
                "latest_date": entries[0]["date"] if entries else None,
            }, HTTPStatus.BAD_REQUEST

        result, scanned = search_csvs(self.data_dir, query, all_columns=False)
        payload = frame_payload(result)
        payload.update(
            {
                "mode": "search",
                "query": query,
                "dates": entries,
                "latest_date": entries[0]["date"] if entries else None,
                "row_count": len(result),
                "scanned_csv_count": scanned,
            }
        )
        return payload, HTTPStatus.OK

    def handle_kline(self, params: dict[str, list[str]]) -> dict:
        ts_code = params.get("ts_code", [None])[0]
        limit = int(params.get("limit", ["120"])[0])

        if not ts_code:
            return {"error": "ts_code parameter is required"}, HTTPStatus.BAD_REQUEST

        try:
            with db_connect() as conn:
                conn.row_factory = sqlite3.Row
                rows = conn.execute(
                    """SELECT trade_date, open, high, low, close, pre_close, vol, amount
                       FROM daily
                       WHERE ts_code = ?
                       ORDER BY trade_date DESC
                       LIMIT ?""",
                    (ts_code, limit),
                ).fetchall()

                if not rows:
                    return {"error": f"No data for {ts_code}"}, HTTPStatus.NOT_FOUND

                # Also get stock name
                name_row = conn.execute(
                    "SELECT name FROM stock_basic WHERE ts_code = ?", (ts_code,)
                ).fetchone()

            items = [dict(r) for r in reversed(rows)]

            return {
                "ts_code": ts_code,
                "name": name_row["name"] if name_row else "",
                "count": len(items),
                "kline": items,
            }, HTTPStatus.OK

        except Exception as e:
            return {"error": str(e)}, HTTPStatus.INTERNAL_SERVER_ERROR

    def send_json(
        self,
        payload: dict[str, object] | tuple[dict[str, object], int],
        status: int = HTTPStatus.OK,
    ) -> None:
        if isinstance(payload, tuple):
            payload, status = payload

        body = json.dumps(payload, ensure_ascii=False).encode("utf-8")
        self.send_response(status)
        self.send_header("Content-Type", "application/json; charset=utf-8")
        self.send_header("Content-Length", str(len(body)))
        self.end_headers()
        self.wfile.write(body)

    def log_message(self, format: str, *args) -> None:
        print(f"{self.address_string()} - {format % args}")


def main() -> int:
    args = parse_args()
    H5Handler.data_dir = args.data_dir.resolve()
    server = ThreadingHTTPServer((args.host, args.port), H5Handler)
    url = f"http://{args.host}:{args.port}"
    print(f"Serving static H5 page: {url}")
    print(f"Reading CSV files from: {H5Handler.data_dir}")
    try:
        server.serve_forever()
    except KeyboardInterrupt:
        print("\nServer stopped.")
    finally:
        server.server_close()
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
