"""Local preview server for the static H5 page.

Usage:
    uv run python h5_server.py
    uv run python h5_server.py --port 8765

The GitHub Pages build uses static JSON generated by export_web_data.py.
This server still exposes a small legacy JSON API for local debugging:
    GET /api/dates
    GET /api/stocks?date=YYYYMMDD
    GET /api/search?q=301297
    GET /api/kline?ts_code=301297.SZ
"""

from __future__ import annotations

import argparse
import json
import re
import sqlite3
from http import HTTPStatus
from http.server import SimpleHTTPRequestHandler, ThreadingHTTPServer
from pathlib import Path
from urllib.parse import parse_qs, urlparse

import pandas as pd

from search_stock_csv import (
    CODE_COLUMNS,
    normalized_column,
    order_columns,
    read_csv,
    relative_path,
    search_csvs,
)
from store.db import connect as db_connect, DB_PATH


ROOT = Path(__file__).resolve().parent
WEB_DIR = ROOT / "web"
DATA_DIR = ROOT / "data"
DATE_RE = re.compile(r"(?<!\d)(20\d{6})(?!\d)")
SYMBOL_RE = re.compile(r"^\d{6}$")


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Serve the stock CSV H5 page.")
    parser.add_argument("--host", default="127.0.0.1")
    parser.add_argument("--port", default=8765, type=int)
    parser.add_argument("--data-dir", default=DATA_DIR, type=Path)
    return parser.parse_args()


def csv_date(path: Path) -> str | None:
    match = DATE_RE.search(path.name)
    return match.group(1) if match else None


def csv_files(data_dir: Path) -> list[Path]:
    if not data_dir.exists():
        return []
    return sorted(data_dir.rglob("*.csv"))


def date_entries(data_dir: Path) -> list[dict[str, object]]:
    grouped: dict[str, list[Path]] = {}
    for path in csv_files(data_dir):
        date = csv_date(path)
        if not date:
            continue
        grouped.setdefault(date, []).append(path)

    entries = []
    for date in sorted(grouped, reverse=True):
        files = grouped[date]
        entries.append(
            {
                "date": date,
                "files": [relative_path(path) for path in files],
                "file_count": len(files),
            }
        )
    return entries


def combine_files(paths: list[Path]) -> pd.DataFrame:
    frames = []
    for path in paths:
        df = read_csv(path)
        df.insert(0, "source_file", relative_path(path))
        frames.append(df)

    if not frames:
        return pd.DataFrame()

    combined = pd.concat(frames, ignore_index=True, sort=False)
    return order_columns(combined)


def frame_payload(df: pd.DataFrame) -> dict[str, object]:
    if df.empty:
        return {"columns": [], "rows": []}

    safe_df = df.fillna("")
    return {
        "columns": list(safe_df.columns),
        "rows": safe_df.to_dict(orient="records"),
    }


def infer_ts_code(symbol: str) -> str | None:
    if not SYMBOL_RE.match(symbol):
        return None
    if symbol.startswith(("60", "68", "90")):
        return f"{symbol}.SH"
    if symbol.startswith(("00", "30", "20")):
        return f"{symbol}.SZ"
    if symbol.startswith(("43", "83", "87", "88", "92")):
        return f"{symbol}.BJ"
    return None


def resolve_ts_code(conn: sqlite3.Connection, raw_code: str) -> str:
    code = raw_code.strip().upper()
    if not code:
        return code

    if "." in code:
        return code

    if SYMBOL_RE.match(code):
        row = conn.execute(
            "SELECT ts_code FROM stock_basic WHERE symbol = ? ORDER BY ts_code LIMIT 1",
            (code,),
        ).fetchone()
        if row:
            return row["ts_code"]

        inferred = infer_ts_code(code)
        if inferred:
            return inferred

    return code


def signal_dates_for_code(data_dir: Path, ts_code: str) -> list[str]:
    dates: set[str] = set()
    symbol = ts_code.split(".", 1)[0].upper()
    variants = {ts_code.upper(), symbol}

    for path in csv_files(data_dir):
        date = csv_date(path)
        if not date:
            continue
        df = read_csv(path)
        normalized_columns = {normalized_column(column): column for column in df.columns}
        code_columns = []
        for candidate in CODE_COLUMNS:
            column = candidate if candidate in df.columns else normalized_columns.get(normalized_column(candidate))
            if column and column not in code_columns:
                code_columns.append(column)
        for column in code_columns:
            values = {str(value).strip().upper() for value in df[column].dropna()}
            if variants & values:
                dates.add(date)
                break

    return sorted(dates)


class H5Handler(SimpleHTTPRequestHandler):
    data_dir = DATA_DIR

    def __init__(self, *args, **kwargs):
        super().__init__(*args, directory=str(WEB_DIR), **kwargs)

    def do_GET(self) -> None:
        parsed = urlparse(self.path)
        if parsed.path == "/api/dates":
            self.send_json(self.handle_dates())
            return
        if parsed.path == "/api/stocks":
            params = parse_qs(parsed.query)
            self.send_json(self.handle_stocks(params))
            return
        if parsed.path == "/api/search":
            params = parse_qs(parsed.query)
            self.send_json(self.handle_search(params))
            return
        if parsed.path == "/api/kline":
            params = parse_qs(parsed.query)
            self.send_json(self.handle_kline(params))
            return
        if parsed.path == "/api/mainline":
            params = parse_qs(parsed.query)
            self.send_json(self.handle_mainline(params))
            return
        if parsed.path == "/":
            self.path = "/index.html"
        super().do_GET()

    def handle_dates(self) -> dict[str, object]:
        entries = date_entries(self.data_dir)
        return {
            "dates": entries,
            "latest_date": entries[0]["date"] if entries else None,
        }

    def handle_stocks(self, params: dict[str, list[str]]) -> tuple[dict[str, object], int]:
        requested_date = params.get("date", [None])[0]
        entries = date_entries(self.data_dir)
        allowed_dates = {entry["date"] for entry in entries}

        if not entries:
            return {
                "error": "No dated CSV files found under data/.",
                "dates": [],
                "latest_date": None,
                "date": None,
                "columns": [],
                "rows": [],
                "files": [],
            }, HTTPStatus.NOT_FOUND

        date = requested_date or entries[0]["date"]
        if date not in allowed_dates:
            return {
                "error": f"Date {date} is not available.",
                "dates": entries,
                "latest_date": entries[0]["date"],
            }, HTTPStatus.BAD_REQUEST

        paths = [path for path in csv_files(self.data_dir) if csv_date(path) == date]
        df = combine_files(paths)
        payload = frame_payload(df)
        payload.update(
            {
                "mode": "date",
                "date": date,
                "dates": entries,
                "latest_date": entries[0]["date"],
                "files": [relative_path(path) for path in paths],
                "row_count": len(df),
            }
        )
        return payload, HTTPStatus.OK

    def handle_search(self, params: dict[str, list[str]]) -> tuple[dict[str, object], int]:
        query = params.get("q", [""])[0].strip()
        entries = date_entries(self.data_dir)
        if not query:
            return {
                "error": "Search query is required.",
                "dates": entries,
                "latest_date": entries[0]["date"] if entries else None,
            }, HTTPStatus.BAD_REQUEST

        result, scanned = search_csvs(self.data_dir, query, all_columns=False)
        payload = frame_payload(result)
        payload.update(
            {
                "mode": "search",
                "query": query,
                "dates": entries,
                "latest_date": entries[0]["date"] if entries else None,
                "row_count": len(result),
                "scanned_csv_count": scanned,
            }
        )
        return payload, HTTPStatus.OK

    def handle_kline(self, params: dict[str, list[str]]) -> dict:
        ts_code = params.get("ts_code", [None])[0]
        limit = int(params.get("limit", ["120"])[0])

        if not ts_code:
            return {"error": "ts_code parameter is required"}, HTTPStatus.BAD_REQUEST

        try:
            with db_connect() as conn:
                conn.row_factory = sqlite3.Row
                ts_code = resolve_ts_code(conn, ts_code)
                rows = conn.execute(
                    """SELECT trade_date, open, high, low, close, pre_close, vol, amount
                       FROM daily
                       WHERE ts_code = ?
                       ORDER BY trade_date DESC
                       LIMIT ?""",
                    (ts_code, limit),
                ).fetchall()

                if not rows:
                    return {"error": f"No data for {ts_code}"}, HTTPStatus.NOT_FOUND

                # Also get stock name
                name_row = conn.execute(
                    "SELECT name FROM stock_basic WHERE ts_code = ?", (ts_code,)
                ).fetchone()

            items = [dict(r) for r in reversed(rows)]

            return {
                "ts_code": ts_code,
                "name": name_row["name"] if name_row else "",
                "count": len(items),
                "kline": items,
                "signal_dates": signal_dates_for_code(self.data_dir, ts_code),
            }, HTTPStatus.OK

        except Exception as e:
            return {"error": str(e)}, HTTPStatus.INTERNAL_SERVER_ERROR

    def send_json(
        self,
        payload: dict[str, object] | tuple[dict[str, object], int],
        status: int = HTTPStatus.OK,
    ) -> None:
        if isinstance(payload, tuple):
            payload, status = payload

        body = json.dumps(payload, ensure_ascii=False).encode("utf-8")
        self.send_response(status)
        self.send_header("Content-Type", "application/json; charset=utf-8")
        self.send_header("Content-Length", str(len(body)))
        self.send_header("Cache-Control", "no-cache, no-store, must-revalidate")
        self.send_header("Pragma", "no-cache")
        self.send_header("Expires", "0")
        self.end_headers()
        self.wfile.write(body)

    def handle_mainline(self, params: dict[str, list[str]]) -> dict:
        """Query main line ranking for a given date from sector_ranking_history."""
        date = params.get("date", [None])[0]
        if not date:
            with db_connect() as conn:
                row = conn.execute(
                    "SELECT MAX(trade_date) FROM sector_ranking_history"
                ).fetchone()
                date = row[0] if row and row[0] else None
            if not date:
                return {"error": "No main line data available"}, HTTPStatus.NOT_FOUND

        try:
            with db_connect() as conn:
                conn.row_factory = sqlite3.Row
                rows = conn.execute(
                    """SELECT trade_date, industry, score, rank,
                              return_5d, return_10d, return_20d,
                              turnover, breadth, new_high_ratio,
                              concentration, relative_strength
                       FROM sector_ranking_history
                       WHERE trade_date = ?
                       ORDER BY rank
                       LIMIT 10""",
                    (date,),
                ).fetchall()

            if not rows:
                return {"error": f"No main line data for {date}"}, HTTPStatus.NOT_FOUND

            sectors = []
            for r in rows:
                d = dict(r)
                sectors.append({
                    "rank": int(d["rank"]),
                    "industry": d["industry"],
                    "score": round(float(d["score"]), 4) if d["score"] else None,
                    "return_5d": round(float(d["return_5d"]), 2) if d["return_5d"] else None,
                    "turnover_billion": round(float(d["turnover"]), 1) if d["turnover"] else None,
                    "breadth_pct": round(float(d["breadth"]), 1) if d["breadth"] else None,
                    "new_high_pct": round(float(d["new_high_ratio"]), 1) if d["new_high_ratio"] else None,
                    "relative_strength": round(float(d["relative_strength"]), 2) if d["relative_strength"] else None,
                })

            signal = None
            if sectors:
                top_score = sectors[0]["score"] if sectors[0]["score"] else 0
                second_score = sectors[1]["score"] if len(sectors) > 1 and sectors[1]["score"] else 0
                gap = round(top_score - second_score, 4)
                consecutive = 1
                with db_connect() as conn:
                    conn.row_factory = sqlite3.Row
                    prev_dates = conn.execute(
                        """SELECT DISTINCT trade_date FROM sector_ranking_history
                           WHERE trade_date < ? ORDER BY trade_date DESC LIMIT 10""",
                        (date,),
                    ).fetchall()
                    for prev_row in prev_dates:
                        pd = prev_row["trade_date"]
                        pt = conn.execute(
                            "SELECT industry FROM sector_ranking_history WHERE trade_date = ? ORDER BY rank LIMIT 1",
                            (pd,),
                        ).fetchone()
                        if pt and pt["industry"] == sectors[0]["industry"]:
                            consecutive += 1
                        else:
                            break

                if top_score >= 0.70 and gap >= 0.10:
                    level = "strong" if consecutive >= 3 else "emerging"
                elif top_score >= 0.70:
                    level = "candidate"
                else:
                    level = "none"

                signal = {
                    "main_line": sectors[0]["industry"],
                    "main_score": top_score,
                    "gap": gap,
                    "consecutive_days": consecutive,
                    "confirmation_level": level,
                    "strength": 2 if level == "strong" else 1 if level in ("emerging", "candidate") else 0,
                    "summary": _mainline_summary(level, sectors[0]["industry"], top_score, consecutive, gap),
                }

            return {
                "date": date,
                "main_line": sectors[0]["industry"] if sectors else None,
                "main_score": sectors[0]["score"] if sectors else None,
                "clarity": (
                    "clear" if signal and signal["confirmation_level"] in ("strong", "emerging")
                    else "fuzzy" if signal else "rotating"
                ),
                "signal": signal,
                "sectors": sectors,
            }, HTTPStatus.OK

        except Exception as e:
            return {"error": str(e)}, HTTPStatus.INTERNAL_SERVER_ERROR

    def log_message(self, format: str, *args) -> None:
        print(f"{self.address_string()} - {format % args}")


def _mainline_summary(level, main_line, score, consecutive, gap):
    if level == "strong":
        return f"✅ 主线确认！{main_line}连续{consecutive}天评分≥0.70，领先{round(gap,2)}，当前评分{round(score,3)}"
    if level == "emerging":
        return f"🟡 主线萌芽：{main_line}评分{round(score,3)}，领先{round(gap,2)}，连续{consecutive}天不足3天"
    if level == "candidate":
        return f"🔵 潜在主线：{main_line}评分{round(score,3)}，领先{round(gap,2)}，需观察持续性"
    return f"⚪ 市场无明显主线"


def main() -> int:
    args = parse_args()
    H5Handler.data_dir = args.data_dir.resolve()
    server = ThreadingHTTPServer((args.host, args.port), H5Handler)
    url = f"http://{args.host}:{args.port}"
    print(f"Serving static H5 page: {url}")
    print(f"Reading CSV files from: {H5Handler.data_dir}")
    try:
        server.serve_forever()
    except KeyboardInterrupt:
        print("\nServer stopped.")
    finally:
        server.server_close()
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
